CREATE PROC FI_SP_IncBeneficiarioV2
    @NOME          VARCHAR (50) ,
    @IDCLIENTE     INT,
	@CPF		   VARCHAR (11)
AS
BEGIN
	INSERT INTO BENEFICIARIOS (NOME, IDCLIENTE, CPF) 
	VALUES (@NOME, @IDCLIENTE,@CPF)

	SELECT SCOPE_IDENTITY()
END